#!/bin/bash
version: "3.9"

services:
  mongo-dev:
    image: prismagraphql/mongo-single-replica:5.0.3
    container_name: mongo-dev
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=monty
      - MONGO_INITDB_ROOT_PASSWORD=pass
    restart: unless-stopped
