name: Lint

on:
  push:
    branches-ignore: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install
      
      - name: Lint
        uses: Adzz/jest_test_action@v1.0.0
        with:
          package-manager: npm
          command: lint
          
  format:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Adzz/jest_test_action@v1.0.0
        with:
          package-manager: npm
          command: format
