name: Lint

on:
  push:
    branches-ignore: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.16.1'

      - name: Install dependencies
        run: npm ci
      
      - name: Run linter
        run: npm run lint

      - name: Check for changes
        id: git-check
        run: echo ::set-output name=changes::$(git status --porcelain)

      - name: Commit and push changes
        if: steps.git-check.outputs.changes != ''
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "work@cedricverlinden.com"
          git add .
          git commit -m "Linting changes"
          git push origin ${{ github.base_ref }}
          
  format:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.16.1'

      - name: Install dependencies
        run: npm ci

      - name: Run formatter
        run: npm run format

      - name: Check for changes
        id: git-check
        run: echo ::set-output name=changes::$(git status --porcelain)

      - name: Commit and push changes
        if: steps.git-check.outputs.changes != ''
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "work@cedricverlinden.com"
          git add .
          git commit -m "Formatting changes"
          git push origin ${{ github.base_ref }}
